---
- name: Include rhel specific vars
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Include distribution specific tasks
  include_tasks: "{{ ansible_os_family }}-setup.yml"
